name: apk_gizi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.0
  go_router: ^6.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_staggered_animations: ^1.0.0
  lottie: ^2.0.0
  intl: ^0.18.1
  percent_indicator: ^4.2.2
  fl_chart: ^0.68.0
  http: ^0.13.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
